### ISSUE TITLE
Attach APK to release?

### ISSUE THREAD

**Issue by IzzySoft** [kloener/visor-android#4]
Would you mind making the `.apk` of your app available here on Github, best with your `releases/` – so people without access to Google Play can get it? Thanks in advance!

**Comment by kloener** [comment]
Done! 👍

**Comment by IzzySoft** [comment]
Thanks! – Though I thought you'd add it [here](https://github.com/kloener/visor-android/releases), see [Creating Releases](https://help.github.com/articles/creating-releases/) ;)

**Comment by kloener** [comment]
:-D Now I did
